/**
 * Языковой файл lang_ru.ts. В нем определены языковые ключи используемые в приложении, все грамотические ошибки можно править здесь ;)
 * @global
 * @see app/_src/js/Common/translate/lang_ru.ts
 * @property  { string } Welcome - это языковой ключ который будет переведен в Добро пожаловать, подобных ключей очень много и они используются по всему приложению,
 */
export var RU: any = {
    'settings': 'Настройки',
    'return': 'Вернуться к списку',
    'search client': 'Поиск клиента',
    'driver': 'Водитель',
    'destination adress': 'Адресс доставки',
    'client phones': 'телефоны клиента',
    'call phone': 'звонили с телефона',
    'add Cient': 'Создание клиента',
    'description': 'Описание',
    'add phone': 'телефон',
    'add adress': 'адрес',
    'fio': 'ФИО',
    'orders open': 'Заказов открыто',
    'orders close': 'Заказов выполнено',
    'order create': 'Создание заказа',
    'create': 'Cоздать',
    'organisations': 'организации',
    'statistics': 'статистика',
    'drivers': 'Водители',
    'operators': 'операторы',
    'clients': 'клиенты',
    'orders': 'заказы',
    'Kover': 'Ковер-Самолет',
    'info': 'Курьерская служба Ковер-Самолет, лидер рынка рынка Кыргызстана доставки продуктов',
    'Tags': 'Теги',
    'Welcome': 'Добро пожаловать',
    'Home': 'Домой',
    'Personal area': 'Личный кабинет',
    'search': 'Поиск',
    'Exit': 'Выход',
    'lang': 'Русский',
    'Filters': 'Фильтры',
    'login': 'Логин',
    'data non correct': 'Данные не корректны',
    'To come in': 'Войти',
    'or': 'или',
    'Request access': 'Запросить доступ',
    'Password': 'Пароль',

};
