/**
 * Языковой файл lang_ru.ts. В нем определены языковые ключи используемые в приложении, все грамотические ошибки можно править здесь ;)
 * @global
 * @see app/_src/js/Common/translate/lang_ru.ts
 * @property  { string } Welcome - это языковой ключ который будет переведен в Добро пожаловать, подобных ключей очень много и они используются по всему приложению,
 */
export var RU: any = {
    'order':'Заказ',
    'search organization':'Поиск Организации',
    'placeholder':'Выберите',
    'save':'Сохранить',
    'cancel':'Отмена',
    'avto number': 'номер машины',
    'add user': 'Добавить пользователя',
    'order sum': 'Сумма вознаграждения',
    'set': 'Установить',
    'sum': 'Сумма',
    'operator pay': 'Ставка оператора',
    'drivers job now':'Водители работают сегодня',
    'client': 'client',
    'organization': 'Организация',
    'rating': 'Рейтинг',
    'operator': 'оператор',
    'order from adress': 'Доставка из',
    'our statistics': 'Вся статистика',
    'statistic operator': 'Статистика по оператору',
    'statistic driver': 'Статистика по водителю',
    'all statistic': 'Статистика по организации',
    'statistic client':'statistic client',
    'organisations': 'Организации',
    'title': 'Название',
    'add organisation': 'Добавить организацию',
    'show': 'Показать',
    'order adress': 'Адрес доставки',
    'date': 'Дата',
    'our clients': 'Наши клиенты',
    'operators': 'Операторы',
    'from': 'от',
    'to': 'до',
    'add operator': 'Создать оператора',
    'add driver': 'Создать водителя',
    'car number': 'Номер машины',
    'rating organisation': 'Рейтинг организаций',
    'phone': 'Телефон',
    'rating client': 'Рейтинг клиентов',
    'adress': 'Адресс',
    'settings': 'Настройки',
    'return': 'Вернуться к списку',
    'search client': 'Поиск клиента',
    'driver': 'Водитель',
    'destination adress': 'Адресс доставки',
    'client phones': 'Телефоны клиента',
    'call phone': 'Звонили с телефона',
    'add Client': 'Создание клиента',
    'description': 'Описание',
    'add phone': 'телефон',
    'add adress': 'адрес',
    'fio': 'ФИО',
    'orders open': 'Заказов открыто',
    'orders close': 'Заказов выполнено',
    'order create': 'Создание заказа',
    'create': 'Cоздать',
    'statistics': 'статистика',
    'drivers': 'Водители',
    'clients': 'клиенты',
    'orders': 'заказы',
    'Kover': 'Ковер-Самолет',
    'info': 'Курьерская служба Ковер-Самолет, лидер рынка рынка Кыргызстана доставки продуктов',
    'Tags': 'Теги',
    'Welcome': 'Добро пожаловать',
    'Home': 'Домой',
    'Personal area': 'Личный кабинет',
    'search': 'Поиск',
    'Exit': 'Выход',
    'lang': 'Русский',
    'Filters': 'Фильтры',
    'login': 'Логин',
    'data non correct': 'Данные не корректны',
    'To come in': 'Войти',
    'or': 'или',
    'Request access': 'Запросить доступ',
    'Password': 'Пароль',
    'job now': 'Работают сегодня',
    'now': 'Сегодня',
    'edit': 'Правка',

};
