export var EN: any = {
    'search organization':'Search Organization',
    'order':'Order',
    'placeholder':'Выберите',
    'save':'Сохранить',
    'cancel':'Отмена',
    'avto number': 'avto number',
    'add user': 'add user',
    'order sum': 'order sum',
    'set': 'set',
    'sum': 'sum',
    'operator pay':'operator pay',
    'drivers job now':'drivers job now',
    'client': 'client',
    'organization': 'organization',
    'rating': 'rating',
    'operator': 'operator',
    'order from adress': 'order from adress',
    'our statistics': 'our statistics',
    'our clients': 'Our clients',
    'add operator': 'add operator',
    'add driver': 'add driver',
    'car number': 'car number',
    'settings': 'settings',
    'add organisation': 'add organisation',
    'rating organisation': 'rating organisation',
    'operators': 'operators',
    'statistic operator': 'statistic operator',
    'statistic driver': 'statistic driver',
    'all statistic': 'all statistic',
    'statistic client':'statistic client',
    'from': 'from',
    'date': 'date',
    'order adress': 'order adress ',
    'to': 'to',
    'show': 'show',
    'rating client': 'rating client',
    'phone': 'phone',
    'adress': 'adress',
    'return': 'return',
    'search client': ' client',
    'driver': 'driver',
    'destination adress': 'destination adress',
    'client phones': 'client phones',
    'call phone': 'call phone',
    'add Client': 'add Client',
    'description': 'description',
    'add phone': 'add phone',
    'add adress': 'add adress',
    'fio': 'Full name',
    'title': 'title',
    'orders open': 'orders open',
    'orders close': 'orders close',
    'order create': 'Order create',
    'create': 'Create',
    'organisations': 'organisations',
    'statistics': 'statistics',
    'drivers': 'drivers',
    'clients': 'clients',
    'orders': 'orders',
    'Kover': 'Ковер-Самолет',
    'Tags': 'Tags',
    'Welcome': 'Welcome',
    'info': 'Курьерская служба Ковер-Самолет, лидер рынка рынка Кыргызстана доставки продуктов',
    'Home': 'Home',
    'Personal area': 'Personal area',
    'Exit': 'Exit',
    'search': 'Search',
    'lang': 'English',
    'Filters': 'Filters',
    'login': 'Login',
    'data non correct': 'The data is not correct',
    'To come in': 'Login',
    'or': 'or',
    'Request access': 'Request access',
    'Password': 'Password',

};