export var EN: any = {
    'data from period': 'data from period',
    'our clients': 'Our clients',
    'add operator': 'add operator',
    'add driver': 'add driver',
    'car number': 'car number',
    'settings': 'settings',
    'rating organisation': 'rating organisation',
    'operators': 'operators',
    'statistic operator': 'statistic operator',
    'statistic driver': 'statistic driver',
    'all statistic': 'all statistic',
    'statistic client':'statistic client',
    'from': 'from',
    'to': 'to',
    'show': 'show',
    'rating client': 'rating client',
    'phone': 'phone',
    'adress': 'adress',
    'return': 'return',
    'search client': ' client',
    'driver': 'driver',
    'destination adress': 'destination adress',
    'client phones': 'client phones',
    'call phone': 'call phone',
    'add Client': 'add Client',
    'description': 'description',
    'add phone': 'add phone',
    'add adress': 'add adress',
    'fio': 'Full name',
    'orders open': 'orders open',
    'orders close': 'orders close',
    'order create': 'Order create',
    'create': 'Create',
    'organisations': 'organisations',
    'statistics': 'statistics',
    'operators': 'operators',
    'drivers': 'drivers',
    'clients': 'clients',
    'orders': 'orders',
    'Kover': 'Ковер-Самолет',
    'Tags': 'Tags',
    'Welcome': 'Welcome',
    'info': 'Курьерская служба Ковер-Самолет, лидер рынка рынка Кыргызстана доставки продуктов',
    'Home': 'Home',
    'Personal area': 'Personal area',
    'Exit': 'Exit',
    'search': 'Search',
    'lang': 'English',
    'Filters': 'Filters',
    'login': 'Login',
    'data non correct': 'The data is not correct',
    'To come in': 'Login',
    'or': 'or',
    'Request access': 'Request access',
    'Password': 'Password',

};