export var EN: any = {
    'return': ' return',
    'search client': ' client',
    'driver': 'driver',
    'destination adress': 'destination adress',
    'client phones': 'client phones',
    'call phone': 'call phone',
    'add Cient': 'add Cient',
    'description': 'description',
    'add phone': 'add phone',
    'add adress': 'add adress',
    'fio': 'Full name',
    'orders open': 'orders open',
    'orders close': 'orders close',
    'order create': 'Order create',
    'create': 'Create',
    'organisations': 'organisations',
    'statistics': 'statistics',
    'operators': 'operators',
    'drivers': 'drivers',
    'clients': 'clients',
    'orders': 'orders',
    'Kover': 'Ковер-Самолет',
    'Tags': 'Tags',
    'Welcome': 'Welcome',
    'info': 'Курьерская служба Ковер-Самолет, лидер рынка рынка Кыргызстана доставки продуктов',
    'Home': 'Home',
    'Personal area': 'Personal area',
    'Exit': 'Exit',
    'search': 'Search',
    'lang': 'English',
    'Filters': 'Filters',
    'login': 'Login',
    'data non correct': 'The data is not correct',
    'To come in': 'Login',
    'or': 'or',
    'Request access': 'Request access',
    'Password': 'Password',

};